import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Varian Blog Feed",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      {children}
    </div>
  );
}
